import { RightOutlined } from "@ant-design/icons";
import { Button, Carousel } from "antd";
import React from "react";

export const ProjectHelpSync = () => {
  const customNextArrow = (onClickHandler, hasPrev, hasNext) => (
    <Button
      type="primary"
      shape="circle"
      icon={<RightOutlined style={{ color: "red" }} />}
      onClick={onClickHandler}
      style={{
        position: "absolute",
        right: 0,
        top: "50%",
        transform: "translateY(-50%)",
      }}
    />
  );
  return (
    <Carousel nextArrow={customNextArrow} autoplay>
      <div>
        <img
          alt="1"
          className="helpModal"
          src="https://firebasestorage.googleapis.com/v0/b/imsavatar-31182.appspot.com/o/files%2FSyncImageIMS%2FProjectAllocation%2FGitlab1.png?alt=media&token=64895125-5c0a-434b-9e77-a9dc07447527"
        />
      </div>
      <div>
        <img
          alt="2"
          className="helpModal"
          src="https://firebasestorage.googleapis.com/v0/b/imsavatar-31182.appspot.com/o/files%2FSyncImageIMS%2FProjectAllocation%2FGitlab2.png?alt=media&token=aee20513-501e-4b9a-ad5a-98bb602416c2"
        />
      </div>
      <div>
        <img
          alt="3"
          className="helpModal"
          src="https://firebasestorage.googleapis.com/v0/b/imsavatar-31182.appspot.com/o/files%2FSyncImageIMS%2FProjectAllocation%2FGitlab3.png?alt=media&token=5cc3b16b-6e2d-49dc-86ef-4ba975233fac"
        />
      </div>
      <div>
        <img
          alt="4"
          className="helpModal"
          src="https://firebasestorage.googleapis.com/v0/b/imsavatar-31182.appspot.com/o/files%2FSyncImageIMS%2FProjectAllocation%2FGitlab4.png?alt=media&token=6324ce99-5967-4daa-aea7-3d30304a62b0"
        />
      </div>
      <div>
        <img
          alt="5"
          className="helpModal"
          src="https://firebasestorage.googleapis.com/v0/b/imsavatar-31182.appspot.com/o/files%2FSyncImageIMS%2FProjectAllocation%2FGitlab5.png?alt=media&token=31d08ead-a4f9-4593-9536-e0babf777c1e"
        />
      </div>
      <div>
        <img
          alt="6"
          className="helpModal"
          src="https://firebasestorage.googleapis.com/v0/b/imsavatar-31182.appspot.com/o/files%2FSyncImageIMS%2FProjectAllocation%2FGitlab6.png?alt=media&token=04a6d874-5769-4dcb-b420-e1afdc44c247"
        />
      </div>
      <div>
        <img
          alt="7"
          className="helpModal"
          src="https://firebasestorage.googleapis.com/v0/b/imsavatar-31182.appspot.com/o/files%2FSyncImageIMS%2FProjectAllocation%2FGitlab7.png?alt=media&token=706b10d5-c6b8-4a36-ad1f-8c80c76958ec"
        />
      </div>
      <div>
        <img
          alt="8"
          className="helpModal"
          src="https://firebasestorage.googleapis.com/v0/b/imsavatar-31182.appspot.com/o/files%2FSyncImageIMS%2FProjectAllocation%2FGitlab8%20(2).png?alt=media&token=d1e55d87-6005-42fb-beb1-a9b0f35afdba"
        />
      </div>
      <div>
        <img
          alt="9"
          className="helpModal"
          src="https://firebasestorage.googleapis.com/v0/b/imsavatar-31182.appspot.com/o/files%2FSyncImageIMS%2FProjectAllocation%2FGitlab9.png?alt=media&token=d7364579-96ef-4187-9c63-751b15f1a9ca"
        />
      </div>
      <div>
        <img
          alt="10"
          className="helpModal"
          src="https://firebasestorage.googleapis.com/v0/b/imsavatar-31182.appspot.com/o/files%2FSyncImageIMS%2FProjectAllocation%2FGitlab10.png?alt=media&token=0c2c3b02-2d07-45b2-b3a6-a5080bd2d1e1"
        />
      </div>
      <div>
        <img
          alt="11"
          className="helpModal"
          src="https://firebasestorage.googleapis.com/v0/b/imsavatar-31182.appspot.com/o/files%2FSyncImageIMS%2FProjectAllocation%2FGitlab11.png?alt=media&token=d2a04d58-68ea-4443-be62-af8e6986a9a6"
        />
      </div>
      <div>
        <img
          alt="12"
          className="helpModal"
          src="https://firebasestorage.googleapis.com/v0/b/imsavatar-31182.appspot.com/o/files%2FSyncImageIMS%2FProjectAllocation%2FGitlab12.png?alt=media&token=bcd2006e-1831-4b98-810e-50ce9a208c11"
        />
      </div>
      <div>
        <img
          alt="13"
          className="helpModal"
          src="https://firebasestorage.googleapis.com/v0/b/imsavatar-31182.appspot.com/o/files%2FSyncImageIMS%2FProjectAllocation%2FGitlab13.png?alt=media&token=8c6c19b7-7329-4532-a78a-84a7228c41c4"
        />
      </div>
      <div>
        <img
          alt="14"
          className="helpModal"
          src="https://firebasestorage.googleapis.com/v0/b/imsavatar-31182.appspot.com/o/files%2FSyncImageIMS%2FProjectAllocation%2FGItlab14.png?alt=media&token=2965545f-637d-4fd7-a31f-8c4cacb31d40"
        />
      </div>
      <div>
        <img
          alt="15"
          className="helpModal"
          src="https://firebasestorage.googleapis.com/v0/b/imsavatar-31182.appspot.com/o/files%2FSyncImageIMS%2FProjectAllocation%2FGitlab15.png?alt=media&token=ab075b7f-99d2-4969-a370-6a57c6589e8c"
        />
      </div>
      <div>
        <img
          alt="16"
          className="helpModal"
          src="https://firebasestorage.googleapis.com/v0/b/imsavatar-31182.appspot.com/o/files%2FSyncImageIMS%2FProjectAllocation%2FGitlab16.png?alt=media&token=d9520e74-14fe-4f8d-9b70-e8237b9ca0f1"
        />
      </div>
      <div>
        <img
          alt="17"
          className="helpModal"
          src="https://firebasestorage.googleapis.com/v0/b/imsavatar-31182.appspot.com/o/files%2FSyncImageIMS%2FProjectAllocation%2FGitlab17.png?alt=media&token=93a889f4-e37d-4ca8-a907-c079360805cc"
        />
      </div>
    </Carousel>
  );
};
